Optimized types
benoitseron/BosonSampling.jl pull request #47
Opened 2022-04-18 20:42 UTC by AntoineRestivo

* ToyModel -> OneParameterInterpolation
* new UserDefinedGramMatrix
* RandomModel -> RandomGramMatrix
* distinguishability -> distinguishability_param (could still be changed in the future)
* Shorter definition of the input

2022-04-18 20:45 UTC, AntoineRestivo commented
The errors in the current main branch (lying in the example_usage) seem to be the same as the ones present when you run this version. Let's fixe them once the pull_request is done however this version should resolve all the errors in the unit test

2022-04-20 16:10 UTC, benoitseron requested changes
nice progress! there are some strange things, like code that you seem to have added (green lines) that is actually mine - maybe you just switched places? same for removing stuff like at_most_one_photon_per_bin etc

2022-04-20 16:10 UTC, benoitseron commented on src/distributions/theoretical_distribution.jl
> +
I believe such long commented bits of code should be removed

2022-04-20 16:10 UTC, benoitseron commented on src/example_usage.jl
> +for x = 0.00001:0.01:1.0
why not start at zero?

2022-04-20 16:10 UTC, benoitseron commented on src/example_usage.jl
> +visualizeData(input, nlist[200], data_exact)
same as above - maybe that the name is a bit too generic too

2022-04-20 16:10 UTC, benoitseron commented on src/partitions/partitions.jl
> +        ev.proba_param2s.probability = EventProbability(mc).probability
typo?

2022-04-20 16:10 UTC, benoitseron commented on src/special_matrices.jl
> +function gram_matrix_one_param(n::Int, x::Float64)
why this restriction? you could 
`@argcheck x>=0 && x<= 1`

2022-04-20 16:10 UTC, benoitseron commented on src/types/input.jl
> +abstract type Gaussian <: InputType end
unless you use this I would remove it - or otherwise let's do supertypes FockInput and GaussianInput etc

2022-04-20 16:10 UTC, benoitseron commented on src/types/input.jl
> +    distinguishability_param::Union{Float64,Nothing}
I would do Real instead (I know it's less efficient but I can explain)

2022-04-29 08:18 UTC, AntoineRestivo commented on src/BosonSampling.jl
> -include("circuits/circuit_elements.jl")
That's strange, look at the current code and this line actually appears

2022-04-29 08:20 UTC, AntoineRestivo commented on src/BosonSampling.jl
> -include("boson_samplers/metropolis_independant_sampler.jl")
Here as well. This line is in the current version

2022-05-12 18:23 UTC, AntoineRestivo commented
@benoitseron Ok I'am back on our project! I've corrected all the commented part except one left that I am not sure to understand, could you enlighten me?

2022-05-12 20:10 UTC, benoitseron commented on src/special_matrices.jl
> +function gram_matrix_one_param(n::Int, x::Float64)
I mean why did you change from Real to Float64? Generally I think that types should not be specified unless the code requires it to make sense, I think it is not seen as very Julia-nic

2022-05-16 09:46 UTC, closed without merging